const NEWS_REQUESTED = 'NEWS_REQUESTED';
const NEWS_RECEIVED = 'NEWS_RECEIVED';
const NEWS_FAILED = 'NEWS_FAILED';
const SHOW_MODAL = 'SHOW_MODAL';
const AUTH_REQUESTED = 'AUTH_REQUESTED';
const AUTH_VERIFY_REQUESTED = 'AUTH_VERIFY_REQUESTED';
const AUTH_SUCCEED = 'AUTH_SUCCEED';
const AUTH_FAILED = 'AUTH_FAILED';
const TOKEN = 'TOKEN';
const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
const USER_REQUESTED = 'USER_REQUESTED';
const USER_RECEIVED = 'USER_RECEIVED';
const USER_FAILED = 'USER_FAILED';
const EDIT_USER_SUCCEED = 'EDIT_USER_SUCCEED';
const EDIT_USER_FAILED = 'EDIT_USER_FAILED';
const EDIT_USER_REQUESTED = 'EDIT_USER_REQUESTED';

export {
  NEWS_FAILED,
  NEWS_RECEIVED,
  NEWS_REQUESTED,
  SHOW_MODAL,
  AUTH_REQUESTED,
  AUTH_VERIFY_REQUESTED,
  AUTH_SUCCEED,
  AUTH_FAILED,
  TOKEN,
  AUTH_SIGN_OUT,
  USER_REQUESTED,
  USER_RECEIVED,
  USER_FAILED,
  EDIT_USER_SUCCEED,
  EDIT_USER_FAILED,
  EDIT_USER_REQUESTED
};
